import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1775565202474 implements MigrationInterface {
    name = 'Migration1775565202474'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "webinars" DROP CONSTRAINT "webinars_host_id_coaches_id_fk"`);
        await queryRunner.query(`ALTER TABLE "webinars" DROP CONSTRAINT "webinars_shadow_host_id_coaches_id_fk"`);
        await queryRunner.query(`ALTER TABLE "webinar_sessions" DROP CONSTRAINT "webinar_sessions_webinar_id_webinars_id_fk"`);
        await queryRunner.query(`ALTER TABLE "webinar_registrations" DROP CONSTRAINT "webinar_registrations_user_id_profiles_id_fk"`);
        await queryRunner.query(`ALTER TABLE "webinar_registrations" DROP CONSTRAINT "webinar_registrations_webinar_id_webinars_id_fk"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "reviews_coach_id_coaches_id_fk"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "reviews_product_id_products_id_fk"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "reviews_user_id_profiles_id_fk"`);
        await queryRunner.query(`ALTER TABLE "purchases" DROP CONSTRAINT "purchases_order_id_orders_id_fk"`);
        await queryRunner.query(`ALTER TABLE "purchases" DROP CONSTRAINT "purchases_product_id_products_id_fk"`);
        await queryRunner.query(`ALTER TABLE "purchases" DROP CONSTRAINT "purchases_user_id_profiles_id_fk"`);
        await queryRunner.query(`ALTER TABLE "user_progress" DROP CONSTRAINT "user_progress_product_id_products_id_fk"`);
        await queryRunner.query(`ALTER TABLE "user_progress" DROP CONSTRAINT "user_progress_user_id_profiles_id_fk"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "products_author_id_coaches_id_fk"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "products_category_id_categories_id_fk"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "orders_coupon_id_coupons_id_fk"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "orders_service_id_coaching_services_id_fk"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "orders_user_id_profiles_id_fk"`);
        await queryRunner.query(`ALTER TABLE "newsletter_subscribers" DROP CONSTRAINT "newsletter_subscribers_coach_id_coaches_id_fk"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "invoices_order_id_orders_id_fk"`);
        await queryRunner.query(`ALTER TABLE "coaches" DROP CONSTRAINT "coaches_user_id_profiles_id_fk"`);
        await queryRunner.query(`ALTER TABLE "coaching_services" DROP CONSTRAINT "coaching_services_coach_id_coaches_id_fk"`);
        await queryRunner.query(`ALTER TABLE "availability" DROP CONSTRAINT "availability_coach_id_coaches_id_fk"`);
        await queryRunner.query(`ALTER TABLE "availability_blocks" DROP CONSTRAINT "availability_blocks_coach_id_coaches_id_fk"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "bookings_coach_id_coaches_id_fk"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "bookings_order_id_orders_id_fk"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "bookings_user_id_profiles_id_fk"`);
        await queryRunner.query(`ALTER TABLE "blog_posts" DROP CONSTRAINT "blog_posts_author_id_profiles_id_fk"`);
        await queryRunner.query(`ALTER TABLE "blog_comments" DROP CONSTRAINT "blog_comments_post_id_blog_posts_id_fk"`);
        await queryRunner.query(`ALTER TABLE "blog_comments" DROP CONSTRAINT "blog_comments_user_id_profiles_id_fk"`);
        await queryRunner.query(`ALTER TABLE "cms_content" DROP CONSTRAINT "cms_content_updated_by_profiles_id_fk"`);
        await queryRunner.query(`ALTER TABLE "gifts" DROP CONSTRAINT "gifts_order_id_orders_id_fk"`);
        await queryRunner.query(`ALTER TABLE "gifts" DROP CONSTRAINT "gifts_product_id_products_id_fk"`);
        await queryRunner.query(`ALTER TABLE "gifts" DROP CONSTRAINT "gifts_redeemed_by_profiles_id_fk"`);
        await queryRunner.query(`ALTER TYPE "spirala_dev_schema"."webinar_status" RENAME TO "webinar_status_old"`);
        await queryRunner.query(`CREATE TYPE "spirala_dev_schema"."webinars_status_enum" AS ENUM('draft', 'published', 'live', 'completed')`);
        await queryRunner.query(`ALTER TABLE "webinars" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "webinars" ALTER COLUMN "status" TYPE "spirala_dev_schema"."webinars_status_enum" USING "status"::"text"::"spirala_dev_schema"."webinars_status_enum"`);
        await queryRunner.query(`ALTER TABLE "webinars" ALTER COLUMN "status" SET DEFAULT 'draft'`);
        await queryRunner.query(`DROP TYPE "spirala_dev_schema"."webinar_status_old"`);
        await queryRunner.query(`ALTER TYPE "spirala_dev_schema"."webinar_session_status" RENAME TO "webinar_session_status_old"`);
        await queryRunner.query(`CREATE TYPE "spirala_dev_schema"."webinar_sessions_status_enum" AS ENUM('scheduled', 'live', 'completed')`);
        await queryRunner.query(`ALTER TABLE "webinar_sessions" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "webinar_sessions" ALTER COLUMN "status" TYPE "spirala_dev_schema"."webinar_sessions_status_enum" USING "status"::"text"::"spirala_dev_schema"."webinar_sessions_status_enum"`);
        await queryRunner.query(`ALTER TABLE "webinar_sessions" ALTER COLUMN "status" SET DEFAULT 'scheduled'`);
        await queryRunner.query(`DROP TYPE "spirala_dev_schema"."webinar_session_status_old"`);
        await queryRunner.query(`ALTER TYPE "spirala_dev_schema"."purchase_status" RENAME TO "purchase_status_old"`);
        await queryRunner.query(`CREATE TYPE "spirala_dev_schema"."purchases_status_enum" AS ENUM('active', 'expired', 'refunded')`);
        await queryRunner.query(`ALTER TABLE "purchases" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "purchases" ALTER COLUMN "status" TYPE "spirala_dev_schema"."purchases_status_enum" USING "status"::"text"::"spirala_dev_schema"."purchases_status_enum"`);
        await queryRunner.query(`ALTER TABLE "purchases" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "spirala_dev_schema"."purchase_status_old"`);
        await queryRunner.query(`ALTER TYPE "spirala_dev_schema"."user_role" RENAME TO "user_role_old"`);
        await queryRunner.query(`CREATE TYPE "spirala_dev_schema"."profiles_role_enum" AS ENUM('user', 'coach', 'admin')`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "role" TYPE "spirala_dev_schema"."profiles_role_enum" USING "role"::"text"::"spirala_dev_schema"."profiles_role_enum"`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "role" SET DEFAULT 'user'`);
        await queryRunner.query(`DROP TYPE "spirala_dev_schema"."user_role_old"`);
        await queryRunner.query(`ALTER TYPE "spirala_dev_schema"."product_type" RENAME TO "product_type_old"`);
        await queryRunner.query(`CREATE TYPE "spirala_dev_schema"."products_product_type_enum" AS ENUM('audio', 'ebook', 'bundle', 'youtube')`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "product_type" TYPE "spirala_dev_schema"."products_product_type_enum" USING "product_type"::"text"::"spirala_dev_schema"."products_product_type_enum"`);
        await queryRunner.query(`DROP TYPE "spirala_dev_schema"."product_type_old"`);
        await queryRunner.query(`ALTER TYPE "spirala_dev_schema"."order_status" RENAME TO "order_status_old"`);
        await queryRunner.query(`CREATE TYPE "spirala_dev_schema"."orders_status_enum" AS ENUM('pending', 'paid', 'refunded')`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "status" TYPE "spirala_dev_schema"."orders_status_enum" USING "status"::"text"::"spirala_dev_schema"."orders_status_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "spirala_dev_schema"."order_status_old"`);
        await queryRunner.query(`ALTER TYPE "spirala_dev_schema"."subscriber_status" RENAME TO "subscriber_status_old"`);
        await queryRunner.query(`CREATE TYPE "spirala_dev_schema"."newsletter_subscribers_status_enum" AS ENUM('active', 'unsubscribed')`);
        await queryRunner.query(`ALTER TABLE "newsletter_subscribers" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "newsletter_subscribers" ALTER COLUMN "status" TYPE "spirala_dev_schema"."newsletter_subscribers_status_enum" USING "status"::"text"::"spirala_dev_schema"."newsletter_subscribers_status_enum"`);
        await queryRunner.query(`ALTER TABLE "newsletter_subscribers" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "spirala_dev_schema"."subscriber_status_old"`);
        await queryRunner.query(`ALTER TYPE "spirala_dev_schema"."discount_type" RENAME TO "discount_type_old"`);
        await queryRunner.query(`CREATE TYPE "spirala_dev_schema"."coupons_discount_type_enum" AS ENUM('fixed', 'percentage')`);
        await queryRunner.query(`ALTER TABLE "coupons" ALTER COLUMN "discount_type" TYPE "spirala_dev_schema"."coupons_discount_type_enum" USING "discount_type"::"text"::"spirala_dev_schema"."coupons_discount_type_enum"`);
        await queryRunner.query(`DROP TYPE "spirala_dev_schema"."discount_type_old"`);
        await queryRunner.query(`ALTER TYPE "spirala_dev_schema"."booking_status" RENAME TO "booking_status_old"`);
        await queryRunner.query(`CREATE TYPE "spirala_dev_schema"."bookings_status_enum" AS ENUM('confirmed', 'completed', 'cancelled', 'no_show')`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "status" TYPE "spirala_dev_schema"."bookings_status_enum" USING "status"::"text"::"spirala_dev_schema"."bookings_status_enum"`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "status" SET DEFAULT 'confirmed'`);
        await queryRunner.query(`DROP TYPE "spirala_dev_schema"."booking_status_old"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "spirala_dev_schema"."booking_status_old" AS ENUM('confirmed', 'completed', 'cancelled', 'no_show')`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "status" TYPE "spirala_dev_schema"."booking_status_old" USING "status"::"text"::"spirala_dev_schema"."booking_status_old"`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "status" SET DEFAULT 'confirmed'`);
        await queryRunner.query(`DROP TYPE "spirala_dev_schema"."bookings_status_enum"`);
        await queryRunner.query(`ALTER TYPE "spirala_dev_schema"."booking_status_old" RENAME TO "booking_status"`);
        await queryRunner.query(`CREATE TYPE "spirala_dev_schema"."discount_type_old" AS ENUM('fixed', 'percentage')`);
        await queryRunner.query(`ALTER TABLE "coupons" ALTER COLUMN "discount_type" TYPE "spirala_dev_schema"."discount_type_old" USING "discount_type"::"text"::"spirala_dev_schema"."discount_type_old"`);
        await queryRunner.query(`DROP TYPE "spirala_dev_schema"."coupons_discount_type_enum"`);
        await queryRunner.query(`ALTER TYPE "spirala_dev_schema"."discount_type_old" RENAME TO "discount_type"`);
        await queryRunner.query(`CREATE TYPE "spirala_dev_schema"."subscriber_status_old" AS ENUM('active', 'unsubscribed')`);
        await queryRunner.query(`ALTER TABLE "newsletter_subscribers" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "newsletter_subscribers" ALTER COLUMN "status" TYPE "spirala_dev_schema"."subscriber_status_old" USING "status"::"text"::"spirala_dev_schema"."subscriber_status_old"`);
        await queryRunner.query(`ALTER TABLE "newsletter_subscribers" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "spirala_dev_schema"."newsletter_subscribers_status_enum"`);
        await queryRunner.query(`ALTER TYPE "spirala_dev_schema"."subscriber_status_old" RENAME TO "subscriber_status"`);
        await queryRunner.query(`CREATE TYPE "spirala_dev_schema"."order_status_old" AS ENUM('pending', 'paid', 'refunded')`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "status" TYPE "spirala_dev_schema"."order_status_old" USING "status"::"text"::"spirala_dev_schema"."order_status_old"`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "spirala_dev_schema"."orders_status_enum"`);
        await queryRunner.query(`ALTER TYPE "spirala_dev_schema"."order_status_old" RENAME TO "order_status"`);
        await queryRunner.query(`CREATE TYPE "spirala_dev_schema"."product_type_old" AS ENUM('audio', 'ebook', 'bundle', 'youtube')`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "product_type" TYPE "spirala_dev_schema"."product_type_old" USING "product_type"::"text"::"spirala_dev_schema"."product_type_old"`);
        await queryRunner.query(`DROP TYPE "spirala_dev_schema"."products_product_type_enum"`);
        await queryRunner.query(`ALTER TYPE "spirala_dev_schema"."product_type_old" RENAME TO "product_type"`);
        await queryRunner.query(`CREATE TYPE "spirala_dev_schema"."user_role_old" AS ENUM('user', 'coach', 'admin')`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "role" TYPE "spirala_dev_schema"."user_role_old" USING "role"::"text"::"spirala_dev_schema"."user_role_old"`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "role" SET DEFAULT 'user'`);
        await queryRunner.query(`DROP TYPE "spirala_dev_schema"."profiles_role_enum"`);
        await queryRunner.query(`ALTER TYPE "spirala_dev_schema"."user_role_old" RENAME TO "user_role"`);
        await queryRunner.query(`CREATE TYPE "spirala_dev_schema"."purchase_status_old" AS ENUM('active', 'expired', 'refunded')`);
        await queryRunner.query(`ALTER TABLE "purchases" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "purchases" ALTER COLUMN "status" TYPE "spirala_dev_schema"."purchase_status_old" USING "status"::"text"::"spirala_dev_schema"."purchase_status_old"`);
        await queryRunner.query(`ALTER TABLE "purchases" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "spirala_dev_schema"."purchases_status_enum"`);
        await queryRunner.query(`ALTER TYPE "spirala_dev_schema"."purchase_status_old" RENAME TO "purchase_status"`);
        await queryRunner.query(`CREATE TYPE "spirala_dev_schema"."webinar_session_status_old" AS ENUM('scheduled', 'live', 'completed')`);
        await queryRunner.query(`ALTER TABLE "webinar_sessions" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "webinar_sessions" ALTER COLUMN "status" TYPE "spirala_dev_schema"."webinar_session_status_old" USING "status"::"text"::"spirala_dev_schema"."webinar_session_status_old"`);
        await queryRunner.query(`ALTER TABLE "webinar_sessions" ALTER COLUMN "status" SET DEFAULT 'scheduled'`);
        await queryRunner.query(`DROP TYPE "spirala_dev_schema"."webinar_sessions_status_enum"`);
        await queryRunner.query(`ALTER TYPE "spirala_dev_schema"."webinar_session_status_old" RENAME TO "webinar_session_status"`);
        await queryRunner.query(`CREATE TYPE "spirala_dev_schema"."webinar_status_old" AS ENUM('draft', 'published', 'live', 'completed')`);
        await queryRunner.query(`ALTER TABLE "webinars" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "webinars" ALTER COLUMN "status" TYPE "spirala_dev_schema"."webinar_status_old" USING "status"::"text"::"spirala_dev_schema"."webinar_status_old"`);
        await queryRunner.query(`ALTER TABLE "webinars" ALTER COLUMN "status" SET DEFAULT 'draft'`);
        await queryRunner.query(`DROP TYPE "spirala_dev_schema"."webinars_status_enum"`);
        await queryRunner.query(`ALTER TYPE "spirala_dev_schema"."webinar_status_old" RENAME TO "webinar_status"`);
        await queryRunner.query(`ALTER TABLE "gifts" ADD CONSTRAINT "gifts_redeemed_by_profiles_id_fk" FOREIGN KEY ("redeemed_by") REFERENCES "profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gifts" ADD CONSTRAINT "gifts_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gifts" ADD CONSTRAINT "gifts_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cms_content" ADD CONSTRAINT "cms_content_updated_by_profiles_id_fk" FOREIGN KEY ("updated_by") REFERENCES "profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blog_comments" ADD CONSTRAINT "blog_comments_user_id_profiles_id_fk" FOREIGN KEY ("user_id") REFERENCES "profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blog_comments" ADD CONSTRAINT "blog_comments_post_id_blog_posts_id_fk" FOREIGN KEY ("post_id") REFERENCES "blog_posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blog_posts" ADD CONSTRAINT "blog_posts_author_id_profiles_id_fk" FOREIGN KEY ("author_id") REFERENCES "profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "bookings_user_id_profiles_id_fk" FOREIGN KEY ("user_id") REFERENCES "profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "bookings_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "bookings_coach_id_coaches_id_fk" FOREIGN KEY ("coach_id") REFERENCES "coaches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "availability_blocks" ADD CONSTRAINT "availability_blocks_coach_id_coaches_id_fk" FOREIGN KEY ("coach_id") REFERENCES "coaches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "availability" ADD CONSTRAINT "availability_coach_id_coaches_id_fk" FOREIGN KEY ("coach_id") REFERENCES "coaches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coaching_services" ADD CONSTRAINT "coaching_services_coach_id_coaches_id_fk" FOREIGN KEY ("coach_id") REFERENCES "coaches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coaches" ADD CONSTRAINT "coaches_user_id_profiles_id_fk" FOREIGN KEY ("user_id") REFERENCES "profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "invoices_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "newsletter_subscribers" ADD CONSTRAINT "newsletter_subscribers_coach_id_coaches_id_fk" FOREIGN KEY ("coach_id") REFERENCES "coaches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "orders_user_id_profiles_id_fk" FOREIGN KEY ("user_id") REFERENCES "profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "orders_service_id_coaching_services_id_fk" FOREIGN KEY ("service_id") REFERENCES "coaching_services"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "orders_coupon_id_coupons_id_fk" FOREIGN KEY ("coupon_id") REFERENCES "coupons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "products_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "products_author_id_coaches_id_fk" FOREIGN KEY ("author_id") REFERENCES "coaches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_progress" ADD CONSTRAINT "user_progress_user_id_profiles_id_fk" FOREIGN KEY ("user_id") REFERENCES "profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_progress" ADD CONSTRAINT "user_progress_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchases" ADD CONSTRAINT "purchases_user_id_profiles_id_fk" FOREIGN KEY ("user_id") REFERENCES "profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchases" ADD CONSTRAINT "purchases_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchases" ADD CONSTRAINT "purchases_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "reviews_user_id_profiles_id_fk" FOREIGN KEY ("user_id") REFERENCES "profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "reviews_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "reviews_coach_id_coaches_id_fk" FOREIGN KEY ("coach_id") REFERENCES "coaches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "webinar_registrations" ADD CONSTRAINT "webinar_registrations_webinar_id_webinars_id_fk" FOREIGN KEY ("webinar_id") REFERENCES "webinars"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "webinar_registrations" ADD CONSTRAINT "webinar_registrations_user_id_profiles_id_fk" FOREIGN KEY ("user_id") REFERENCES "profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "webinar_sessions" ADD CONSTRAINT "webinar_sessions_webinar_id_webinars_id_fk" FOREIGN KEY ("webinar_id") REFERENCES "webinars"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "webinars" ADD CONSTRAINT "webinars_shadow_host_id_coaches_id_fk" FOREIGN KEY ("shadow_host_id") REFERENCES "coaches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "webinars" ADD CONSTRAINT "webinars_host_id_coaches_id_fk" FOREIGN KEY ("host_id") REFERENCES "coaches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
