export interface AudioChapter {
  id: string;        // UUID corto (8 chars) o número secuencial
  name: string;      // Nombre del capítulo
  duration: number;  // Duración en minutos (para compatibilidad)
  durationSeconds: number; // ✅ Duración en segundos (nuevo campo estándar)
  url?: string;      // URL opcional (solo si hay archivo)
  filename?: string; // Nombre del archivo (opcional)
  desc?: string;     // Descripción opcional (abreviado)

  // SEO Content Enhancement
  transcript?: string; // Transcripción completa del capítulo
  transcriptSummary?: string; // Resumen de la transcripción
  transcriptKeywords?: string[]; // Palabras clave del contenido
}

export interface AudioProduct {
  id: string; // "curso-meditacion-es", "curso-meditacion-en"
  originalId: string; // "curso-meditacion" (para relacionar idiomas)
  slug?: string; // SEO-friendly URL slug
  name: string;
  description: string;
  highlightDescription?: string; // Descripción destacada/cita
  author?: string; // Author/narrator of the audio course
  language: 'en' | 'es' | 'pl';
  emoji: string; // Emoji del curso (🧘‍♀️, 📚, 🎵, etc.)
  
  // Contenido específico del idioma
  chapters: AudioChapter[];
  lessons: number;
  totalDuration: number; // en minutos
  
  // Precios por idioma (puede variar por mercado)
  basePrices: {
    pnl: number;
    usd: number;
    eur: number;
  };
  
  // Métricas
  rating: number;
  totalReviews: number;
  isActive: boolean;
  
  // Environment tag: 'test' or 'prod'
  environment: 'test' | 'prod';
  
  // Estado de archivado
  archived: boolean;
  archivedAt?: string | Date;
  archivedBy?: string;
  archiveReason?: string;
  
  // Timestamps
  createdAt: string | Date;
  updatedAt?: string | Date;
  
  // Cover image
  coverUrl?: string;      // URL completa de la portada (legacy fallback)
  coverUrls?: {           // Responsive cover URLs (generated by ImageProcessingService)
    thumbnail: string;    // 200px - for lists, carousels, cart
    small: string;        // 400px - mobile phones
    medium: string;       // 800px - tablets
    large: string;        // 1280px - HD desktop
    xlarge?: string;      // 1920px - Full HD
    original: string;     // 3840px - 4K UHD maximum quality
  };
  coverPath?: string;     // Path en Storage (e.g., "audios/audioId/cover.jpg")

  // Metadatos específicos de audio
  audioFormat: 'mp3' | 'wav' | 'm4a';
  quality: '128kbps' | '256kbps' | '320kbps' | 'lossless';
  
  // Categorías
  category: string;
  tags: string[];
  
  // Información del instructor (puede variar por idioma)
  instructor: {
    name: string;
    bio?: string;
    avatar?: string;
    nativeLanguage?: string; // Idioma nativo del instructor
  };
  
  // Metadatos de relación entre idiomas
  relatedLanguages: string[]; // ["es", "en", "pl"]
  originalLanguage: string; // "es" si fue creado en español
  
  // Configuración de disponibilidad por idioma
  availability: {
    enabled: boolean;
    releaseDate?: string | Date; // Cuándo estará disponible en este idioma
    earlyAccess?: boolean; // Acceso anticipado
  };
  
  // Stripe Integration
  stripe?: {
    productId?: string;      // Stripe Product ID
    priceIds?: {             // Stripe Price IDs por moneda
      pln?: string;
      usd?: string;
      eur?: string;
    };
    lastSynced?: string;     // Última sincronización con Stripe
  };
}

export interface CreateAudioData {
  name: string;
  description: string;
  author?: string; // Author/narrator of the audio course
  language: 'en' | 'es' | 'pl';
  emoji: string; // Emoji del curso (🧘‍♀️, 📚, 🎵, etc.)
  chapters: AudioChapter[];
  lessons: number;
  totalDuration: number;
  basePrices: {
    pnl: number;
    usd: number;
    eur: number;
  };
  audioFormat: 'mp3' | 'wav' | 'm4a';
  quality: '128kbps' | '256kbps' | '320kbps' | 'lossless';
  category: string;
  tags: string[];
  instructor: {
    name: string;
    bio?: string;
    avatar?: string;
    nativeLanguage?: string;
  };
  relatedLanguages?: string[];
  availability?: {
    enabled: boolean;
    releaseDate?: string | Date;
    earlyAccess?: boolean;
  };
  environment?: 'test' | 'prod'; // Default to current environment
  archived?: boolean; // Por defecto false

  // Cover image
  coverUrl?: string;
  coverPath?: string;
}

export interface UpdateAudioData extends Partial<CreateAudioData> {
  isActive?: boolean;
  rating?: number;
  totalReviews?: number;
  archived?: boolean;
  archiveReason?: string;
  coverUrl?: string;
  coverPath?: string;
}

// Interfaz para productos relacionados en diferentes idiomas
export interface RelatedAudioProducts {
  originalId: string;
  products: {
    [language: string]: AudioProduct;
  };
  availableLanguages: string[];
  defaultLanguage: string;
}
