export interface CoachingSession {
  id: string;
  name: string;
  description: string;
  duration: number; // en minutos
  price: number;
  isActive: boolean;
}

export interface CoachingProduct {
  id: string;
  slug?: string; // SEO-friendly URL slug
  name: string;
  description: string;
  highlightDescription?: string; // Quote/highlight for marketing (like ebooks/audios)
  emoji: string; // Emoji del coaching (🌟, 🎯, 💪, etc.)
  sessions: CoachingSession[];
  basePrices: {
    pnl: number;
    usd: number;
    eur: number;
  };
  rating: number;
  totalReviews: number;
  isActive: boolean;
  createdAt: string | Date;
  updatedAt?: string | Date;

  // Environment tag: 'test' or 'prod'
  environment: 'test' | 'prod';

  // Cover image (consistent with ebooks/audios)
  coverUrl?: string;      // URL completa de la portada (legacy fallback)
  coverUrls?: {           // Responsive cover URLs (generated by ImageProcessingService)
    thumbnail: string;    // 200px - for lists, carousels, cart
    small: string;        // 400px - mobile phones
    medium: string;       // 800px - tablets
    large: string;        // 1280px - HD desktop
    xlarge?: string;      // 1920px - Full HD
    original: string;     // 3840px - 4K UHD maximum quality
  };
  coverPath?: string;     // Path en Storage (e.g., "coaching/coachingId/cover.jpg")

  // Metadatos específicos de coaching
  language: 'en' | 'es' | 'pl';
  sessionDuration: number; // duración estándar en minutos
  maxSessionsPerDay: number;

  // Categorías
  category: string;
  tags: string[];
  
  // Información del coach
  coach: {
    name: string;
    bio?: string;
    avatar?: string;
    specialties: string[];
    experience: number; // años de experiencia
  };
  
  // Configuración de disponibilidad
  availability: {
    timezone: string;
    workingHours: {
      start: string; // formato "09:00"
      end: string;   // formato "17:00"
    };
    workingDays: ('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday')[];
  };
  
  // Métodos de comunicación
  communicationMethods: {
    whatsapp: boolean;
    googleMeet: boolean;
    zoom: boolean;
    phone: boolean;
  };
  
  // Stripe Integration
  stripe?: {
    productId?: string;      // Stripe Product ID
    priceIds?: {             // Stripe Price IDs por moneda
      pln?: string;
      usd?: string;
      eur?: string;
    };
    lastSynced?: string;     // Última sincronización con Stripe
  };
}

export interface CreateCoachingData {
  name: string;
  description: string;
  highlightDescription?: string; // Quote/highlight for marketing
  emoji: string; // Emoji del coaching (🌟, 🎯, 💪, etc.)
  sessions: CoachingSession[];
  basePrices: {
    pnl: number;
    usd: number;
    eur: number;
  };
  // Cover image fields (set after upload)
  coverUrl?: string;
  coverUrls?: {
    thumbnail: string;
    small: string;
    medium: string;
    large: string;
    original: string;
  };
  coverPath?: string;
  language: 'en' | 'es' | 'pl';
  sessionDuration: number;
  maxSessionsPerDay: number;
  category: string;
  tags: string[];
  coach: {
    name: string;
    bio?: string;
    avatar?: string;
    specialties: string[];
    experience: number;
  };
  availability: {
    timezone: string;
    workingHours: {
      start: string;
      end: string;
    };
    workingDays: ('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday')[];
  };
  communicationMethods: {
    whatsapp: boolean;
    googleMeet: boolean;
    zoom: boolean;
    phone: boolean;
  };
  environment?: 'test' | 'prod'; // Default to current environment
}

export interface UpdateCoachingData extends Partial<CreateCoachingData> {
  isActive?: boolean;
}
