export interface EbookChapter {
  id: string;
  name: string;
  number: number;
  content: string;
  pageCount: number;
  summary?: string;
}

export interface EbookProduct {
  id: string;
  slug?: string; // SEO-friendly URL slug
  name: string;
  description: string;
  emoji: string; // Emoji del ebook (📖, 📚, 🎯, etc.)
  chapters: EbookChapter[];
  totalPages: number;
  basePrices: {
    pnl: number;
    usd: number;
    eur: number;
  };
  rating: number;
  totalReviews: number;
  isActive: boolean;

  // Environment tag: 'test' or 'prod'
  environment: 'test' | 'prod';

  // Estado de archivado
  archived: boolean;
  archivedAt?: string | Date;
  archivedBy?: string;
  archiveReason?: string;

  createdAt: string | Date;
  updatedAt?: string | Date;

  // Metadatos específicos de ebook
  format: 'pdf' | 'epub' | 'mobi';
  language: 'en' | 'es' | 'pl';
  fileSize: number; // en MB

  // ✅ File storage information (similar to AudioChapter)
  fileUrl?: string;     // URL completa del archivo en Storage
  fileName?: string;    // Nombre del archivo (e.g., "ebookId.pdf")
  filePath?: string;    // Path en Storage (e.g., "ebooks/ebookId/ebookId.pdf")

  // Cover image
  coverUrl?: string;      // URL completa de la portada (legacy fallback)
  coverUrls?: {           // Responsive cover URLs (generated by ImageProcessingService)
    thumbnail: string;    // 200px - for lists, carousels, cart
    small: string;        // 400px - mobile phones
    medium: string;       // 800px - tablets
    large: string;        // 1280px - HD desktop
    xlarge?: string;      // 1920px - Full HD
    original: string;     // 3840px - 4K UHD maximum quality
  };
  coverPath?: string;     // Path en Storage (e.g., "ebooks/ebookId/cover.jpg")
  
  // Categorías
  category: string;
  tags: string[];
  
  // Información del autor
  author: {
    name: string;
    bio?: string;
    avatar?: string;
  };

  // Información de publicación
  publicationDate: string | Date;
  isbn?: string;
  publisher?: string;

  // Highlight description (quote for marketing)
  highlightDescription?: string;

  // SEO Content Enhancement
  faqs?: Array<{
    question: string;
    answer: string;
  }>;

  // Stripe Integration
  stripe?: {
    productId?: string;      // Stripe Product ID
    priceIds?: {             // Stripe Price IDs por moneda
      pln?: string;
      usd?: string;
      eur?: string;
    };
    lastSynced?: string;     // Última sincronización con Stripe
  };
}

export interface CreateEbookData {
  name: string;
  description: string;
  emoji: string; // Emoji del ebook (📖, 📚, 🎯, etc.)
  chapters: EbookChapter[];
  totalPages: number;
  basePrices: {
    pnl: number;
    usd: number;
    eur: number;
  };
  format: 'pdf' | 'epub' | 'mobi';
  language: 'en' | 'es' | 'pl';
  fileSize: number;
  category: string;
  tags: string[];
  author: {
    name: string;
    bio?: string;
    avatar?: string;
  };
  publicationDate: string | Date;
  isbn?: string;
  publisher?: string;
  highlightDescription?: string;
  environment?: 'test' | 'prod'; // Default to current environment
  archived?: boolean; // Por defecto false

  // ✅ File storage information
  fileUrl?: string;
  fileName?: string;
  filePath?: string;

  // Cover image
  coverUrl?: string;
  coverPath?: string;
}

export interface UpdateEbookData extends Partial<CreateEbookData> {
  isActive?: boolean;
  archived?: boolean;
  archiveReason?: string;
  fileUrl?: string;
  fileName?: string;
  filePath?: string;
  coverUrl?: string;
  coverPath?: string;
}
